ALTER TABLE "Website" ADD COLUMN "userId" INTEGER;
UPDATE "Website" SET "userId" = 1 WHERE "userId" IS NULL;
ALTER TABLE "Website" ALTER COLUMN "userId" SET NOT NULL;
ALTER TABLE "Website" ADD CONSTRAINT "Website_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;